@Component
export struct Article {
  build() {
    List() {
      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })

      ListItem() {
        Column() {
          // 图片、标题、描述
          Row() {
            Image($r('app.media.family')).width(140)
            Column() {
              Text('IT从业者如何养生').margin({ bottom: 10 })
              Text('多吃些富含维生素A,C和蛋白质的食物，多喝些茶，多吃水果喝素菜粗粮')
            }
            .layoutWeight(1)
            .alignItems(HorizontalAlign.Start)
            .margin({ left: 5 })
          }.alignItems(VerticalAlign.Top)

          // 类型、阅读
          Row() {
            Text('专家专业版').fontColor('#a4c8fe')
            Text('392003人阅读').fontColor('#ccc')
          }.width('100%').justifyContent(FlexAlign.SpaceBetween)
        }.padding(10).backgroundColor(Color.White).borderRadius(10).margin({ top: 10 })
      }.padding({ left: 20, right: 20 })
    }.width('100%').height('100%')
  }
}